### ISSUE TITLE
unknown transformation name es6

### ISSUE THREAD

**Issue by lougreenwood** [sandydoo/ember-cli-es6-transform#3]
Hello, I'm getting this error:

```
while import node_modules/@mobiscroll/javascript/dist/js/mobiscroll.javascript.min.js: found an unknown transformation name es6. Available transformNames are: fastbootShim,amd
```

This is what I have in environment.js:
```
  app.import('node_modules/@mobiscroll/javascript/dist/js/mobiscroll.javascript.min.js', {
    using: [
      { transformation: 'es6', as: 'mobiscroll.js' }
    ]
  });
```

```
ember-cli: 3.1.4
node: 10.0.0
os: darwin x64
```

Any ideas? Thanks

**Comment by sandydoo** [comment]
Are you developing an app or an addon?

I haven't been able to replicate the issue using your ember-cli/node version. All I can suggest for now is that you double-check that `ember-cli-es6-transform` is indeed installed.

**Comment by lougreenwood** [comment]
Developing an app - I’ll double check that it’s installed.. Are there any known issues with Fastboot?

**Comment by sandydoo** [comment]
> Are there any known issues with Fastboot?

Not really. The app I just tested with uses FastBoot.

**Comment by lougreenwood** [comment]
hmm, seems it simply was just missing from package.json... strange but simple to solve - thanks for your help 😄
